# Лабораторная работа №3. NumPy
## Задание
1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [2]:
import numpy as np

arr = np.random.random((10, 10))
print("Минимум:", arr.min())
print("Максимум:", arr.max())

Минимум: 0.011026065721207123
Максимум: 0.9895237421711497


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [3]:
chessboard = np.zeros((8, 8), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1
print("Шахматная доска:")
print(chessboard)

Шахматная доска:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [4]:
z = np.arange(11)
z[(z > 3) & (z < 8)] *= -1
print("Массив после изменения знака:")
print(z)


Массив после изменения знака:
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [5]:
z = np.random.rand(5, 10)
row_means = z.mean(axis=1, keepdims=True)
z_normalized = z - row_means
print("Исходная матрица:")
print(z)
print("Нормализованная матрица:")
print(z_normalized)

Исходная матрица:
[[0.65885446 0.13107625 0.70621693 0.43067446 0.39818819 0.59075675
  0.41375118 0.77085653 0.3161873  0.5608661 ]
 [0.48481047 0.03595023 0.14951549 0.09098974 0.74886    0.50006168
  0.54024077 0.42504791 0.09060229 0.70446064]
 [0.38434069 0.17004716 0.81444387 0.8851203  0.68150478 0.50669636
  0.26771517 0.74286377 0.32649081 0.12984362]
 [0.10878355 0.94892296 0.22088365 0.19397741 0.28301841 0.43122918
  0.65499402 0.7667675  0.14791086 0.98556894]
 [0.58772856 0.32079732 0.32587499 0.66536487 0.7732404  0.94663817
  0.39360842 0.19153135 0.38450381 0.14795293]]
Нормализованная матрица:
[[ 0.16111165 -0.36666657  0.20847411 -0.06706835 -0.09955462  0.09301393
  -0.08399163  0.27311372 -0.18155551  0.06312329]
 [ 0.10775655 -0.34110369 -0.22753843 -0.28606418  0.37180608  0.12300776
   0.16318684  0.04799398 -0.28645163  0.32740672]
 [-0.10656597 -0.32085949  0.32353721  0.39421364  0.19059813  0.01578971
  -0.22319148  0.25195712 -0.16441585 -0.36106303]
 [-0.3

5. Поменяйте 1 и 2 строки матрицы

In [6]:
z = np.arange(25).reshape(5,5)
z[[0, 1]] = z[[1, 0]]
print("Матрица после замены строк:")
print(z)

Матрица после замены строк:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [7]:
z = np.random.random((10,2))
x, y = z[:, 0], z[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar_coords = np.column_stack((r, theta))
print("Полярные координаты:")
print(polar_coords)

Полярные координаты:
[[0.71306965 1.51932849]
 [0.48481091 0.36209451]
 [1.15471558 0.95397465]
 [0.69413998 1.22861249]
 [1.01224106 1.25062836]
 [0.80085355 1.12480825]
 [0.35166567 0.73135274]
 [1.04196522 0.75276819]
 [0.95726228 0.73349168]
 [0.57840173 0.02339934]]


7. Заменить максимальный элемент массива на ноль

In [8]:
z = np.random.random(10)
max_index = np.argmax(z)
z[max_index] = 0
print("Массив после замены максимума:")
print(z)

Массив после замены максимума:
[0.77314815 0.03999146 0.83392885 0.48493213 0.         0.65717156
 0.14982966 0.61002586 0.21764395 0.21773713]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [9]:
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
np.add.at(z, i, 1)
print("Массив после добавления:")
print(z)

Массив после добавления:
[3. 3. 3. 2. 5. 2. 4. 2. 3. 3.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [10]:
z = np.array([1, 2, 3, 4, 5])
result = np.zeros(len(z) + (len(z)-1)*3)
result[::4] = z
print("Вектор с нулями:")
print(result)

Вектор с нулями:
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [11]:
z = np.arange(100)
v = np.random.uniform(0, 100)
nearest = z[np.argmin(np.abs(z - v))]
print(f"Ближайшее к {v:.2f} число: {nearest}")

Ближайшее к 84.78 число: 85


# Ответы на вопросы
## 1.Типы массивов:

```
# np.array([1, 4, 2, 5, 3]) → int64

np.array([1., 4, 2, 5, 3]) → float64

np.array([1, 4, 2, 5, 3], dtype='float128') → float128

np.array([1., 4, 2, 5, 3], dtype='complex128') → complex128

np.array([1, 4, 2, 5, 3], dtype='float64') → float64

np.array([1, 4, 2, 5, 3], dtype=int64) → int64

np.array([1, 4, 2, 5, 3], dtype='bool') → bool

np.array([1, 4, 2, 5, 3], dtype='str') → str

np.array([1, 4, 2, 5, '3']) → str

np.array([1, -4, 2, 0, 1j]) → complex128
```

## 2.Результаты операций:

```
# np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1' - '41' (конкатенация строк)
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1] - -4 (0 or -4 = -4)
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1] - 0 (0 and -4 = 0)
np.array([1, -4, 2, 0, True], dtype='int64')[-1] - 1 (True преобразуется в 1)
np.array([1, -4, 2, 0, 1j], dtype='int64')[1] - Ошибка (нельзя преобразовать комплексное число в int)
np.array([1, -4, 2, 0, 1j], dtype='str')[-1] - '1j'
np.array([1, 4, 2, 5, '3'])[-1] * 3 -'333'
```

## 3.Результаты создания массивов:

```
np.ones((3, 5), dtype=float) - Массив 3x5 из единиц типа float
np.full((3, 5), 3.14) - Массив 3x5 со значением 3.14
np.linspace(0, 1, 5) - [0. 0.25 0.5 0.75 1. ]
np.diag((1,3,5)) - Диагональная матрица с элементами 1,3,5
np.smile((1,3,5)) - Ошибка (нет функции np.smile)
np.random.random((3, 3)) - Случайная матрица 3x3
np.eye(3) - Единичная матрица 3x3
np.empty(3) - Неинициализированный массив размера 3
```
## 4.Индексация массива X:

```
3, 7, [4], [4 8], [[3 5] [7 6]], [6 8], [7 6 8 8], [[3 5 2 4] [7 6 8 8] [1 6 7 7]], тот же что и предыдущий, [[3 2] [1 7]], [[3 2] [1 7]], развернутый массив
```
## 5.Различие split:

```
np.split(grid, [2]) - разделение по строкам

np.split(grid, [2], axis=1) - разделение по столбцам
```
## 6.Различие операций сложения:

```
[1, 2, 3] + [3, 2, 1] = [1, 2, 3, 3, 2, 1] (конкатенация списков)

np.array([1, 2, 3]) + np.array([3, 2, 1]) = [4, 4, 4] (поэлементное сложение)
```

## 7.Измерение времени в Colab:

```
%timeit код_для_измерения
```
или


```
import time
start = time.time()
# код
end = time.time()
print(f"Время выполнения: {end - start} сек")
```

## 8.Результаты операций с X:

```
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M) - np.sum(X) = 69
np.sum(M, axis=1) - np.sum(X, axis=1) = [14, 29, 21]
np.sum(M, axis=0) - np.sum(X, axis=0) = [11, 17, 17, 19]
np.sum(M, axis=2) - Ошибка (нет оси 2)
np.sum(M, 1) - Аналогично axis=1
sum(M) - Сумма по первому измерению
sum(M,1) - Ошибка (неправильный синтаксис)
```
## 9.Булева индексация:

```
X = np.array([1,2,3,4])

X > 3 - [False False False True]
X < 3 - [True True False False]
X[X < 3] -[1 2]
X[X > 3] - [4]
X[X != 3] -[1 2 4]
```

## 10.Преимущества NumPy:

- Быстродействие (оптимизированные C-функции)

- Векторизованные операции

- Эффективное использование памяти

- Удобные математические функции

- Обширная функциональность для работы с массивами

